"""Resume-Job Matcher v1 contracts."""

from app.ai.job_matcher.constants import (
    JOB_MATCHER_SKILL_NAME,
    JOB_MATCHER_VERSION,
    MAX_JOB_MATCHER_ATTEMPTS,
)
from app.ai.job_matcher.prompt import JOB_MATCHER_PROMPT_V1
from app.ai.job_matcher.schemas import (
    EvidenceSourceType,
    GapImportance,
    GateAssessment,
    GateEvidence,
    MatcherInput,
    MatcherOutput,
    MatchGap,
    RequirementAssessment,
    ResumeEvidenceItem,
    ResumeEvidenceRef,
)
from app.ai.job_matcher.scoring import (
    DIMENSION_MAX,
    EVIDENCE_CAP,
    DimensionScore,
    MatchRankingCandidate,
    MatchRankingResult,
    MatchScoringError,
    MatchScoringResult,
    RankedMatch,
    ScoredRequirement,
    calculate_confidence_level,
    calculate_recommendation_level,
    rank_match_candidates,
    round_score_for_display,
    score_match,
)
from app.ai.job_matcher.service import JobMatcherResult, match_job
from app.ai.job_matcher.validator import validate_matcher_output
from app.domain.matching import (
    AssessmentStatus,
    ConfidenceLevel,
    EligibilityStatus,
    EvidenceGrade,
    MatchDimension,
    MatchLevel,
    RecommendationLevel,
)

__all__ = [
    "JOB_MATCHER_SKILL_NAME",
    "JOB_MATCHER_PROMPT_V1",
    "JOB_MATCHER_VERSION",
    "MAX_JOB_MATCHER_ATTEMPTS",
    "AssessmentStatus",
    "ConfidenceLevel",
    "DIMENSION_MAX",
    "DimensionScore",
    "EVIDENCE_CAP",
    "EligibilityStatus",
    "EvidenceGrade",
    "EvidenceSourceType",
    "GapImportance",
    "GateAssessment",
    "GateEvidence",
    "JobMatcherResult",
    "MatchGap",
    "MatchDimension",
    "MatchLevel",
    "MatchRankingCandidate",
    "MatchRankingResult",
    "MatchScoringError",
    "MatchScoringResult",
    "MatcherInput",
    "MatcherOutput",
    "RequirementAssessment",
    "RecommendationLevel",
    "RankedMatch",
    "ResumeEvidenceItem",
    "ResumeEvidenceRef",
    "ScoredRequirement",
    "calculate_confidence_level",
    "calculate_recommendation_level",
    "match_job",
    "rank_match_candidates",
    "round_score_for_display",
    "score_match",
    "validate_matcher_output",
]
